language: python

# Takes inspiration from https://github.com/tornadoweb/tornado/blob/master/.travis.yml
.mixins:
- &xenial-mixin
  dist: xenial
  sudo: true
  addons:
    apt:
      packages:
        - libgnutls-dev

stages:
  - test
  - name: deploy
    if: type != pull_request

jobs:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - <<: *xenial-mixin
      python: 3.7

    - stage: deploy
      python: 3.6
      script: python -m statik.cmdline --upload=netlify --netlify-site-id=$NETLIFY_SITE_ID -p examples/blog

install:
  - "pip install -r requirements.txt"

script: python -m unittest discover
